Repository saitamau-maximum/public-website, pull requests merged in 2024-04, with the labels that each got.

#65 feat: headerのモバイルデザインを追加、ハンバーガーメニューの実装など
  src/components/Header/Header.module.scss
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
Labels: ❇️ 新機能, デザイン

#73 fix: font not loaded correctly
  src/app/global.css
  src/app/layout.tsx
Labels: 🔧 バグ修正

#92 docs: サイトリニューアルのニュースを追加
  docs/news/test.md
  docs/news/website-migration.md
Labels: ✏️ ドキュメント, 🔧 バグ修正
